import React from "react";

const Categories = () => {
  return (
    <div>
      <b>Categories...</b>
      <div>
        Inspirational
        <div>
          Humor
          <div>
            Science-Fiction
            <div>
              Self Improvement
              <div>Literature</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Categories;
